# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  zarf-templates: https://raw.githubusercontent.com/buzzdeploy/dd-task-ci-templates/initialize_repo/.taskfile/zarf.yaml
  #deploy-templates: https://raw.githubusercontent.com/buzzdeploy/dd-task-ci-templates/initialize_repo/deploy/taskfile.yml
  #test-templates: https://raw.githubusercontent.com/buzzdeploy/dd-task-ci-templates/initialize_repo/test/does-the-name-matter.yml
tasks:
  default:
    cmds:
      - task: zarf-templates:create
        vars: { ZARF_DIR: './retro' }
      #- task: deploy-templates:hello
      #- task: test-templates:hello
